version: '3'
services: 
  web:
    image: nginx
    container_name: nginx-1
    ports:
      - "8080:80"
      # Uso del volumen creado
    volumes: 
      - "vol2:/usr/share/nginx/hmtl"
# Creacion del volumen
volumes:
  vol2: